### ISSUE TITLE
Questions about AutoCast Dataset

### ISSUE THREAD

**Issue by bbuing9** [andyzoujm/autocast#4]
Hi, first of all, thanks for the great work and the efforts to make it open-source.

I believe that this is a really interesting direction and has huge potential. 

Actually, I have a few questions about the construction process of AutoCast as follows:

1. How do you generate each forecasting question? Did humans write each forecasting question upon some "gold (i.e., evidence or source) article," similar to other QA datasets such as Natural Question or SQuAD?
    1-1. If yes, would you provide the used gold articles?
2. When I open the AutoCast dataset, there is some relevant metadata (background or source links). Would you provide some detailed explanations for each metadata?

Thank you very much.

**Comment by andyzoujm** [comment]
Thank you for your interest. The questions are collected from prediction markets like [Metaculus](https://www.metaculus.com). Since forecasting involves making a judgement about a future event, there are no gold articles prior to the resolution date, just more relevant articles. But you could probably find some "gold" articles after an event has occurred (some might appear in the community comments). For more details please check out our [paper](https://arxiv.org/pdf/2206.15474.pdf) and the README (which contains explanations for each field).
